services:
  - type: web
    name: membba-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
